name: testflow

on:
  push:
    branches: [ main ] 

env: 
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_DB: test
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker containers
        run: .github/docker-compose.yml build 

      - name: run docker containers
        run: |
          echo --- Running test cases ---
          docker-compose up --exit-code-from api
          echo --- Completed test cases ---
  
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: .github/docker-compose.yml build
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: publish
        run: .github/docker-compose.yml push